Conversion from vcf to pgen + pvar + psam (plink2 --make-pgen) failed with the following error:
```
Error: Invalid QUAL value on line 268 of
/share/PI/mrivas/data/1000genomes/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes-pgen-temporary.pvar.
```

- 1KG_vcf2pgen.12668561.{sh, out, err}
  - script file, stdout, stderr
- ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes-pgen.log
  - log file from plink2

 Changes to be committed:
	new file:   1KG_vcf2pgen.12668561.err
	new file:   1KG_vcf2pgen.12668561.out
	new file:   1KG_vcf2pgen.12668561.sh
	new file:   1KG_vcf2pgen.sbatch
	new file:   20170208_pgenlib.ipynb